export const pathname = {
  WORK_THROUGH: '/',
  CHALLENGE: '/challenge',
  SIGN_UP: '/sign-up',
  LOGIN: '/login',
  ACCOUNT: '/account',
  FORGET_PASSWORD: '/forget-password',
  BADGE: '/badge',
  BADGE_HISTORY: '/badge/history',
  BADGE_TAKEN: '/badge/taken',
  COMMENT_CHALLENGE: '/challenge/comment',
  CREATE_CHALLENGE: '/challenge/create',
  DETAIL_CAHLLENGE: '/challenge/detail',
  SETTING: '/setting',
  PROFILE: '/setting/profile',
  WITHDRAWAL: '/setting/withdrawal',
  RESET_PASSWORD: '/setting/reset-password',
  NOTIFICATION: '/setting/notification',
};
