import type { Metadata, Viewport } from 'next';
import './globals.css';
import { ClientLayout } from './client-layout';
import { BackgroundLayout } from './(pages)/background-layout';
import { WebViewControl } from './webViewControl';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-VK2931MXB6');
        `}
      </Script>
      <body
        className="w-screen h-screen font-SUIT"
        style={{
          background: 'linear-gradient(0deg, #302773 0%, #0E0D1A 100%)',
        }}
      >
        <ClientLayout>
          <div className="w-full h-full  max-w-[500px] mx-auto relative">
            {children}
            <BackgroundLayout />
            {/* <WebViewControl /> */}
          </div>
        </ClientLayout>
        <div id="modal-root" />
      </body>
    </html>
  );
}
